module.exports = {
  tabWidth: 2,
  trailingComma: "all",
  singleQuote: false,
  semi: true,
  plugins: [require.resolve("@trivago/prettier-plugin-sort-imports")],
  importOrder: [
    "^./src/components/(.*)$",
    "^./src/pages/(.*)$",
    "^./src/context/(.*)$",
    "^./src/services/(.*)$",
    "^./src/utils/(.*)$",
    "^./src/config/(.*)$",
    "^./src/__tests__/(.*)$",
    "^./src/styles/(.*)$",
    "^./src/hooks/(.*)$",
    "^./src/templates/(.*)$",
    "^./src/stories/(.*)$",
    "^[./]",
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  importOrderCaseInsensitive: true,
};
